# Generated by Django 2.0.1 on 2018-01-09 19:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaID', models.CharField(max_length=10)),
                ('asalk', models.CharField(max_length=100)),
                ('Data', django.contrib.postgres.fields.jsonb.JSONField(default={'LicenseKey': '', 'timestamp': ''})),
            ],
        ),
        migrations.CreateModel(
            name='AUA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auaID', models.CharField(max_length=20)),
                ('Data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('asa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authenticate.ASA')),
            ],
        ),
    ]
