# Generated by Django 2.0.1 on 2018-01-14 21:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('uid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('auth_status', models.CharField(default='T', max_length=1)),
                ('lang_code', models.CharField(max_length=2)),
                ('PIN', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=60)),
                ('lname', models.CharField(max_length=80)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('address', django.contrib.postgres.fields.jsonb.JSONField(default={'country': '', 'dist': '', 'house': '', 'lm': '', 'loc': '', 'pc': '', 'po': '', 'state': '', 'street': '', 'subdist': '', 'vtc': ''})),
                ('laddress', django.contrib.postgres.fields.jsonb.JSONField(default={'country': '', 'dist': '', 'house': '', 'lm': '', 'loc': '', 'pc': '', 'po': '', 'state': '', 'street': '', 'subdist': '', 'vtc': ''})),
                ('care_of', models.CharField(max_length=60)),
                ('lcare_of', models.CharField(max_length=80)),
                ('photo', models.ImageField(upload_to='')),
                ('bios', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
    ]
