# Generated by Django 2.0.1 on 2018-01-15 18:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_auto_20180115_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='isVerfied',
            new_name='isVerified',
        ),
    ]
